### ISSUE TITLE
Questions, not a bug: Difference between sign-in and login

### ISSUE THREAD

**Issue by jakehockey10** [Angular2Guy/AngularPwaMessenger#14]
Hello!  I stumbled across your repo after looking through https://dzone.com/articles/draft-an-angular-pwa-from-frontend-to-backend-the because I was curious how to accomplish the similar task of how to allow offline use of at least a portion of the angular app I'm building for work.  Sometimes, our technicians will be in a setting where the internet is not available.  We have a feature module that we recently added to our angular app that is basically a specific engineering calculation calculator.  At first, we were writing an electron application, but decided to move the functionality to our website and attempt to build a PWA that allowed offline access instead.  Managing more than one application with the size of our development team seemed infeasible, especially if the electron app doesn't really have a ton of functionality on its own.

We use Azure AD B2C for authentication when the user is online, so we don't actually have a login form of our own as we use the redirect flow for B2C authentication.  Hence, I'm contemplating what the best (convenient, yet secure) user experience is for logging in while offline.  So far, I'm thinking that for offline use, a separate password just for offline use could be created at first, and the user would have to use that password instead of their B2C password to authenticate offline.

I'm using this repo as inspiration for implementing this, but I'm a bit confused about something in your login component.  There is a login and a sign-in.  What are the differences there?  It isn't immediately obvious to me why there is a tab for logging in and a tab for signing in.  Is sign-in actually a sign-up flow in this app?  I notice that the sign-in form has a password confirmation field in addition to the password field.

In addition to this question, I was wondering if you see any problems with the approach I'm trying to take here.  Our angular app never sees the B2C password, so I can't easily use their existing password for the local login unless I ask them to give it to me again once in the angular app.  I'm thinking that when the app recognizes the user is offline, it could go to a new login component in the angular app similar to the one in this repo, and the user could create a secure password or provide their own if they don't already exist in the local-db, otherwise login with the password they chose to use for offline local login.

Are you aware of any issues with the browser's `window.crypto` in terms of security?  Would the only thing I should really be concerned with be brute force password detection?  I'm not really savvy when it comes to security in general, and I have to admit I'm not at all sure how this hides a user's password.  I know it uses encryption, but how does the encryption stay secure if everything is client side?  What prevents a "bad guy" from decrypting encrypted information if everything is client-side?

I'm really sorry for the long message here, and if you have the time to respond, I would greatly appreciate it.  If you don't have the time to respond, I still greatly appreciate you putting all this together and sharing it with the public.

**Comment by Angular2Guy** [comment]
Hello, I will answer the Questions where I have knowhow. 
With the singin the user account with username and password hash is created. With the login the user logs in his account. The username and the password are put in input components and are available to the PWA. The password confirmation input is to make the user type in the password twice to reduce the possibility of typos. The window.crypto api is implemented in the browser. The Firefox and Chromium browsers are open source. If you have doubts about the implementation of the window.crypto api you could have it checked by an expert you trust. For me the concepts look plausible. The important part is to hash the password and then store the hashcode. You can check the password with the hashcode but you cannot get the password from the hashcode -> one way only. In the PWA the password is hashed on client and server. To decrypt messages the password is needed and that is only availible in memory when the user is logged in. The security depends on the quality of the users password and a malicious actor would have to get it while the user is logged in. 
I am not sure the PWA concept can be applied to your application because your user logs in with a different service. That means the user has to be online to login.

**Comment by jakehockey10** [comment]
Thanks for the response!

What I was thinking was that for feature modules that require being accessible offline could require the user to have a separate password for offline use.  If the PWA recognizes that the application is offline, it could require the user to enter the separate password for offline functionality to access encrypted data for this particular feature module.  I don't like the idea of the user having to remember two different passwords, but if they need this, I don't see any other alternative.

What I was most confused by was how to keep the private key secure, but I think I understand that now.  Does the private key get imported, but cannot be exported, and that's why it is secure?  And you would have to provide the password to decrypt any of the data along with the private key?

I'm struggling with figuring out how to provide what they are asking for.  But at the end of the day, this feature module doesn't require any data accessed by a server, all the calculations are done client side with inputs provided by the end user.  The real desire here is to confirm that the user is assigned the role necessary to provide access to the feature module.  If I can save the user profile to indexed db in an encrypted fashion while online, my thought is that the user profile information with their assigned roles could be read from indexed db to confirm their roles, but they couldn't just go into indexed db/local storage and change their roles after the fact to give them access when they haven't been assigned.

Any other advice or thoughts on the matter would be greatly appreciated!

**Comment by Angular2Guy** [comment]
There is 'sign' and 'verify' in the SubtleCrypto api. With Public/Private Keys your requirement should the be possible. You will need to verify the signature. I have not used the calls yet. You will have read about it figure out howto implement you requirements. That is all the advise I can give.
